service:
  name: serverless-online-sastry
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  getAllPujas:
    handler: functions/index.getAllPujas
    events:
      - http:
          method: get
          path: pujas
  getPujaById:
    handler: functions/index.getPujaById
    events:
      - http:
          method: get
          path: pujas
